ip_address: ""
serial_port: "/dev/serial/by-id/usb-Hokuyo_Data_Flex_for_USB_URG-Series_USB_Driver-if00"
serial_baud: "115200"
frame_id: "laser"
calibrate_time: "true"
publish_intensity: "false"
publish_multiecho: "false"
angle_min: "-2.0944"
angle_max: "2.0944"